### ISSUE TITLE
Deploy directory doesn't exist without docker volume

### ISSUE THREAD

**Issue by FunDeckHermit** [torizon/torizoncore-builder#1]
Hi,

These are the step's I've taken:
```
# Setup the environment
cd /srv/builder-tool
source tcb-env-setup.sh -d -s /srv/builder-tool/storage

# Get the reference image
cd /srv/builder-tool/images
wget https://artifacts.toradex.com/artifactory/torizoncore-oe-prod-frankfurt/dunfell-5.x.y/release/13/apalis-imx6/torizon-upstream/torizon-core-docker/oedeploy/torizon-core-docker-apalis-imx6-Tezi_5.6.0+build.13.tar
tar -xvkf {name_of_image}+build.x.tar
mv {name_of_image}+build.x apalis-imx6-img
```

My tcbuild.yaml looks like this:
```
input:
  easy-installer:
    local: images/apalis-imx6-img
customization:
  device-tree:
    include-dirs:
      - device-trees/include/
    custom: device-trees/dts-arm32/imx6dl-colibri-eval-v3.dts
    overlays:
      add:
        - device-trees/overlays/display-edt7_overlay.dts
output:
  easy-installer:
    local: nondocker.CUSTOM
```

Then building yields the following error: `Error: Deploy sysroot directory /deploy does not exist.`
![image](https://user-images.githubusercontent.com/5075692/179231596-cbc3f486-8426-4a10-9e32-c601d8e88697.png)

Deploying the branch afterwards doesn't work either:
![image](https://user-images.githubusercontent.com/5075692/179232994-54fbf3f6-d67e-402e-8152-989e6008ec75.png)
